scene:
  type: "InteractiveTraversableScene"
  scene_model: "Pomaria_1_int"

objects:
  - type: "DatasetObject"
    name: "teacup"
    category: "teacup"
    model: "vckahe"
    position: [-2.74713, -2.52066, 1.0]

  - type: "DatasetObject"
    name: "knife"
    category: "carving_knife"
    model: "alekva"
    position: [-2.34713, -2.06784, 1.0]

  # - type: "DatasetObject"
  #   name: "sugar jar"
  #   category: "jar_of_sugar"
  #   model: "pnbbfb"
  #   position: [0, -0.1, 1.0]

  - type: "DatasetObject"
    name: "tablespoon"
    category: "tablespoon"
    model: "huudhe"
    position: [-2.37511, -2.49872, 1.0]

robots:
  - type: "UR5e"
    name: "UR5e"
    obs_modalities: ["rgb", "depth"]
    position: [-3.1, -2, 1.0]
    orientation: [0, 0, 0, 1]
    action_normalize: False,
    controller_config:
      arm_0:
        name: JointController
        command_input_limits: None
        use_delta_commands: False
      gripper_0:
        name: MultiFingerGripperController
        mode: binary

# task:
#   type: GraspTask
#   obj_name: teacup

# cam_pos:
#   position: [-0.18768, -1.86944, 2.22927]
#   orientation: [0.37, 0.39, 0.61, 0.58]

# potential_pos:
#   [-2.74713, -2.52066, 1.0]